version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: db-board
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: board
    volumes:
      - ./data:/var/lib/postgresql/data